// genesis

/**********************************************************************
**
**	DO NOT EDIT THIS FILE IN THE neurokit DIRECTORY!
**
**	Make a copy of this file in every directory that contains .p
**	files and edit the copies, in order to customize neurokit for
**	different simulations. When you run neurokit from other
**	directories, the simulator will look for the local version of
**	userprefs.g, and if it cannot find it there will look for the
**	default in the neurokit directory. This version of userprefs is
**	set up to run the Coarse Asymmetric Mitral cell demo.
**	
**	There are three aspects to customisation :
**	
**    	1	Include the appropriate script files from the /neuron/prototype
**  		directory and from wherever you have defined new prototype
**		elements.
**
**    	2	Invoke the functions that make the prototypes you want for
**		your simulation.
**
**	3	Put your preferences for the user_variables defined in
** 		defaults.g in the copies of this file.
**
**********************************************************************/

echo Using local user preferences!

/**********************************************************************
**
**	1	Including script files for prototype functions
**
**********************************************************************/

/* file for standard compartments */
include compartments 

/* file for voltage-gated pyramidal cell channels */
include CA1pyr_chanb14

/* file for CA1 excitatory and inhibitory synaptic channels */
include CA1_synchan0

// standard spike generator
include protospike

/************************************************************************
**  2	Invoking functions to make prototypes in the /library element
************************************************************************/

/*   To ensure that all subsequent elements are made in the library    */
	pushe /library


	/* Make the standard types of compartments  */

	make_cylind_compartment		/* makes "compartment" */
	make_sphere_compartment		/* makes "compartment_sphere" */
	make_cylind_symcompartment	/* makes "symcompartment" */
	make_sphere_symcompartment	/* makes "symcompartment_sphere" */

	/* Assign some constants */
	EREST_ACT = -0.065       // resting membrane potential (volts)
	float ELEAK = -0.075    // leak potential
	float ENA = 0.120 + EREST_ACT //  0.055
	float EK = -0.015 + EREST_ACT // -0.080
	float ECA = 0.145 + EREST_ACT // 0.080

	/* Make CA1 pyramidal cell channels */

	make_Na
	make_K_DR

	make_K_M

	make_CaT // T-type Ca channel
        make_CaL // L-type Ca channel
        make_CaN // N-type Ca channel
        make_CaR // R-type Ca channel

	make_Ca_conc

        make_K_AHP
	make_K_C
		
	make_K_A_prox // improved K_A channels (proximal and
	make_K_A_dist // distal) based on Hoffman et al., 1997

	make_H_CA1pyr_prox // hippocampal I(h) channels (proximal and
	make_H_CA1pyr_dist // distal) based on Magee (1998)
	
//	make_NaP // persistent Na channel - not included in current model

	/* These are some synaptic channels */
	make_Ex_channel
	make_NMDA
//	make_Inh_channel
	make_fast_Inh_channel
	make_slow_Inh_channel

	/* returning to the root element */
	pope

/*************************************************************** *******
**
**	3	Setting preferences for user-variables.
**
**********************************************************************/

/* See defaults.g for default values of these. Put your preferred
   values for these in your copy of userprefs in the directory from
   which you are running your simulations. */

// user_symcomps = 1 // symmetric
user_intmethod = 11

user_syntype1 = "Ex_channel"
user_syntype2 = "fInh_channel"
user_help = "README"
user_name = "Szabolcs Kali"
user_cell = "/pc1a"
user_pfile = "pc1a_r3s17n.p"

float user_wx = 6.47e-4  // wx, wy, cx, cy, cz for the draw widget
float user_wy = 6.47e-4
float user_cx = 1.25e-4
float user_cy = 0.0
float user_cz = 0.2e-3

// Set the scales for the graphs in the two cell windows
user_ymin1 = -0.1
user_ymax1 = 0.15
user_xmax1 = 0.5
user_xmax2 = 0.5
user_ymin2 = 0.0
user_ymax2 = 5e-7
user_yoffset2 = 0.0

